apiVersion: v2
name: multitenant-app
description: A Helm chart for Multi-Tenant Application with Backend, Frontend, PostgreSQL, Redis, and Kafka
type: application
version: 1.0.0
appVersion: "1.0.0"

Keywords:
  - multitenant
  - nodejs
  - react
  - PostgreSQL
  - Redis
  - Kafka

maintainers:
  - name: SpiderMan Peter
  - email: spidermanpeter018@gmail.com