apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multitenant-app
  labels:
    app: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
      - name: backend
        image: sxmpath577/multi-tenant-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
