apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ include "multitenant-app.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "multitenant-app.labels" . | nindent 4 }}
data:
  BACKEND_URL: {{ tpl .Values.configMap.data.BACKEND_URL . | quote }}
  FRONTEND_URL: {{ tpl .Values.configMap.data.FRONTEND_URL . | quote }}
  
  DATABASE_HOST: {{ tpl .Values.configMap.data.DATABASE_HOST . | quote }}
  DATABASE_PORT: {{ .Values.configMap.data.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .Values.postgres.database | quote }}
  DATABASE_USER: {{ .Values.postgres.username | quote }}
  
  REDIS_HOST: {{ tpl .Values.configMap.data.REDIS_HOST . | quote }}
  REDIS_PORT: {{ .Values.configMap.data.REDIS_PORT | quote }}
  
  KAFKA_BROKERS: {{ tpl .Values.configMap.data.KAFKA_BROKERS . | quote }}
  
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }} 
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  
  ENVIRONMENT: {{ .Values.global.environment | quote }}