{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multitenant-app.fullname" . }}-kafka-client
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "multitenant-app.kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: kafka
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "multitenant-app.kafka.selectorLabels" . | nindent 4 }}
{{- end }}
