{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multitenant-app.fullname" . }}-kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "multitenant-app.kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
      protocol: TCP
      name: kafka
  selector:
    {{- include "multitenant-app.kafka.selectorLabels" . | nindent 4 }}
  clusterIP: None
{{- end }}