{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled (not .Values.postgres.persistence.useStatefulSetVolumeClaimTemplates) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "multitenant-app.fullname" . }}-postgres-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "multitenant-app.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
