{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multitenant-app.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "multitenant-app.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
      protocol: TCP
      name: redis
  selector:
    {{- include "multitenant-app.redis.selectorLabels" . | nindent 4 }}
{{- end }}