{{- if and .Values.kafka.enabled .Values.kafka.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multitenant-app.fullname" . }}-zookeeper
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "multitenant-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kafka.zookeeper.service.port }}
      targetPort: client
      protocol: TCP
      name: client
    - port: 2888
      targetPort: server
      protocol: TCP
      name: server
    - port: 3888
      targetPort: leader-election
      protocol: TCP
      name: leader-election
  selector:
    {{- include "multitenant-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
  clusterIP: None
{{- end }}