apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: multitenant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:3.7.0
        ports:
        - containerPort: 9092
        envFrom:
        - configMapRef:
            name: app-config
