apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: multitenant-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
